// <auto-generated />
using System;
using Master_in_Web_APPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Master_in_Web_APPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240129073908_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Master_in_Web_APPI.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "VN",
                            Color = "Green",
                            Gender = "M",
                            Price = 12.199999999999999,
                            Size = 10
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "LP",
                            Color = "Maroon",
                            Gender = "M",
                            Price = 13.199999999999999,
                            Size = 13
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "Coco",
                            Color = "yellow",
                            Gender = "F",
                            Price = 13.9,
                            Size = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
